# Generated by Django 4.2.1 on 2023-06-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_token_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="token",
            name="Token",
        ),
        migrations.AddField(
            model_name="token",
            name="token",
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
